name: GitHub Actions Test
on: [push]
jobs:
  docker-info:
    runs-on: ubuntu-latest
    steps:
      - run: docker info
  alpine-faccessto2-test:
    runs-on: ubuntu-latest
    container: alpine:3.14
    steps:
      - run: apk --no-cache add gcc libc-dev
      - run: printf '#include <fcntl.h>\n#include <unistd.h>\n#include <stdio.h>\n#include <sys/syscall.h>\nint main(){int ret = syscall(SYS_faccessat2, 0, "/",  R_OK, AT_EACCESS); printf("ret = %%d\\n", ret);}' > foo.c
      - run: gcc foo.c
      - run: ./a.out
  stuff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: docker build -t foobar .
      - run: docker run --rm foobar
      - run: |
          docker run -i --rm foobar
      - run: |
          script -q /dev/null -c "docker run -it --rm foobar"
  bar:
    runs-on: ubuntu-latest
    needs: stuff
    steps:
      - run: echo "This shows that the docker cache is not shared"
      - run: ! docker run --rm foobar
