name: GitHub Actions Test
on: [push]
jobs:
  alpine-faccessto2-test:
    runs-on: ubuntu-latest
    container: alpine:3.14
    steps:
      - run: apk --no-cache add gcc libc-dev
      - run: printf '#include <fcntl.h>\n#include <unistd.h>\n#include <stdio.h>\n#include <sys/syscall.h>\nint main(){int ret = syscall(SYS_faccessat2, 0, "/",  R_OK, AT_EACCESS); printf("ret = %%d\\n", ret);}' > foo.c
      - run: gcc foo.c
      - run: ./a.out
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: docker info
      - run: pwd; ls
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
      - run: pwd; ls
      - name: Cache Source Code (not a great example, who cares)
        uses: actions/cache@v2
        with:
          path: |
            ~/work
      - run: pwd; ls
      # - run: docker build -t foobar .
      - run: docker buildx build -t foobar .
      - run: docker run --rm foobar
      - run: |
          docker run -i --rm foobar
      - run: |
          script -q /dev/null -c "docker run -it --rm foobar"
  bar:
    runs-on: ubuntu-latest
    needs: foo
    steps:
      - run: echo "This shows that not even the docker cache is shared between jobs"
      - run: |
          ! docker run --rm foobar
